services:
  mongo-dev:
    image: mongo:8.2.1
    container_name: mongo_calendar_dev
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

    cpus: 6.0
    mem_limit: 4G

    command: [ "mongod", "--wiredTigerCacheSizeGB", "2" ]

volumes:
  mongo_data:
